### ISSUE TITLE
Rendering text to the screen

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#10]
How do I render text to the screen? I saw the method [SpriteBatch.DrawString (SpriteFont, String, Vector2, Color)](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.spritebatch.drawstring.aspx) but that needs a SpriteFont and I haven't figured out how to add one to a monogame project.

**Comment by WasabiFan** [comment]
You can [get a spritefont](https://msdn.microsoft.com/en-us/library/bb197848(v=xnagamestudio.31).aspx) from the content manager. It would be easiest to use one of the fonts that I have already added (for the menu) from the [content folder](https://github.com/kyranstar/Hunt-The-Wumpus/tree/master/Final%20Game/Content) -- you just pass the name of one of those files to that `LoadContent` method that I linked to above.

**Comment by kyranstar** [comment]
Okay, cool. Thanks.
