### ISSUE TITLE
Scale doesn't work

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#11]
If you change the scale of a sprite, it doesn't render as scaled.

**Comment by WasabiFan** [comment]
Hmmm... docs are pretty vague on this, but all the sources that I can find say that it should scale the sprite.  I'll check this out.

**Comment by kyranstar** [comment]
I think the reason it's not working is that we're passing it a rectangle, so it can't scale up because it's confined. If we do this instead 

    Target.Draw(Texture, new Vector2(RenderX, RenderY), rotation: Rotation, color: DrawColor * Opacity, scale: new Vector2(Scale));

It works.

**Comment by WasabiFan** [comment]
Ahhh I was looking over the MonoGame source last week to try to find the issue, and traced the calls as if we weren't passing in a rectangle. If we are, that would explain it. Nice find!

**Comment by WasabiFan** [comment]
Please commit that fix when you get the chance.

P.S. Include the phrase "closes #11" in your commit message to automatically link and close the issue.
