### ISSUE TITLE
Add gold and bats to renderer

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#14]

**Comment by WasabiFan** [comment]
I have added both gold and pits, and added a temporary bat picture for debugging Now we just need real pictures.

**Comment by WasabiFan** [comment]
@nikbyk Any progress on a bat image?

**Comment by nikbyk** [comment]
Added bat image, but it seems to not move with the bat after you run into it

**Comment by WasabiFan** [comment]
> it seems to not move with the bat after you run into it

I saw that too... not sure why it happens. I'll look into it.

P.S. I don't see a recent commit from you -- have you pushed yet?

**Comment by nikbyk** [comment]
I have


Sent by Outlook for Android





On Sun, May 17, 2015 at 9:41 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
> it seems to not move with the bat after you run into it

I saw that too... not sure why it happens. I'll look into it.

P.S. I don't see a recent commit from you -- have you pushed yet?

---

**Comment by WasabiFan** [comment]
> I have

You mean that you have committed and pushed? It's not in the repo on GH as far as I can tell.

**Comment by nikbyk** [comment]
thats odd, ill try again

**Comment by nikbyk** [comment]
that should do it

**Comment by WasabiFan** [comment]
I think I have figured out why the image isn't changing.

P.S. I love your commit message :wink:
> merge.... something...

**Comment by nikbyk** [comment]
Lol, yes. I had no clue what the conflict was


Sent by Outlook for Android





On Sun, May 17, 2015 at 9:50 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
I think I have figured out why the image isn't changing.

P.S. I love your commit message :wink:
> merge.... something...

---

**Comment by WasabiFan** [comment]
I think it was [this](https://github.com/kyranstar/Hunt-The-Wumpus/commit/5152533f02d7193338e59bb08201f48ea1d78ff4#diff-28dc489df23f4adb7ec6c7b66cae9390L154). It probably just resolved itself.

**Comment by nikbyk** [comment]
did you figure out why the picture did not travel with the bats?

**Comment by WasabiFan** [comment]
I just pushed a commit to fix this. There is a problem, though: As soon as you hit the key to enter a bat room, the bat collision is registered and you are moved to a different room. You can see the images by running `display rooms` in the debug console for now.

**Comment by nikbyk** [comment]
Also, there are a few problems with the random maps. You and I should work on those tomorrow in class. Are the guys coming in on friday?

**Comment by WasabiFan** [comment]
> Are the guys coming in on friday?

As I understand it, we won't see them again until the competition. But I still do want to meet at least once a week, maybe more, so that we know what we want to work on.

@kyranstar what's your feeling on the random maps? What needs to be done to make them ready for use? It would be nice for the three of us to sit down and discuss this tomorrow.

**Comment by nikbyk** [comment]
Ideally, we should meet every day, but at least 3 times this week


Sent by Outlook for Android





On Sun, May 17, 2015 at 10:56 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
> Are the guys coming in on friday?

As I understand it, we won't see them again until the competition. But I still do want to meet at least once a week, maybe more, so that we know what we want to work on.

@kyranstar what's your feeling on the random maps? What needs to be done to make them ready for use? It would be nice for the three of us to sit down and discuss this tomorrow.

---

**Comment by WasabiFan** [comment]
@nikbyk Do you have a gold image? It really just needs to be a cherry in the center of the image, and the image should be the same aspect ratio of the cave image. This is the one image that I think should have margin built-in to it.

**Comment by WasabiFan** [comment]
The gold and bats show up now and fade away when you hit them.
