### ISSUE TITLE
General discussion on graphics technology/platform

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#2]
There was a small discussion of this in #1, but I'm opening a new issue to discuss our platform options in more detail.

There are three core categories for base frameworks that we can start with: barebones rendering engines, helper game wrappers/frameworks, and game engines. Here's a list of the pros and cons of each along with some examples of each (feel free to point out more details if you think of anything; this is just a braindump):

## Low-down rendering engines
**Examples:** 
 - DirectX (with managed wrapper)

### Pros
- Very performant
- I can't think of anything else...

### Cons
- Complicated
- Not always well-documented
- Takes lots of work for even basic tasks
- Doesn't include UX primitives
- Assets become hard to manage
- Not cross-platform

## Helper wrappers
**Examples:** 
 - MonoGame 
   - open-source 
   - cross-platform implementation of XNA
   - Hundreds of games already made

### Pros
- Reasonably fast
- Handles some of the complexities of graphics
- Doesn't require much installation/setup for development
- Can be cross-platform using Xamarin (requires a paid license) 
- Often open-source (developed in the open)
- Often available through NuGet

### Cons
- Still requires some manual setup (custom boilerplate)
- Doesn't include UX primitives
- Assets become hard to manage

## Game engines
**Examples:** 
 - Paradox3D
   - Very new, may be few examples but has nice documentation
   - Duality
   - WYSIWYG editor
   - Fully editable in VIsualStudio (instead of editor)

### Pros
- Easiest of the three to get started with (not much boilerplate)
- Includes things like UI controls, physics engines, audio systems, etc
- Good maintainability
- Can be cross-platform using Xamarin (requires a paid license) 
- Often open-source (although may be maintained separately/privately)

### Cons
- Slowest (although not enough that it should become a problem)
- Requires most dependencies for development
- Probably largest binary footprint

## Conclusion
In the end, I think this topic will definitely require more discussion. I think using a bare-metal library like DirectX is overkill and not worth the effort for our scale, but the other two options are open for debate. In the end, I would tend to vote for the third option ("game engine") because it will probably allow us to produce the best product in the shortest amount of time, but I am open to others' opinions.

So... what do you think?

### Footnote
One other thing to consider is if we want to pursue cross-platform. With either of the last two options we should be able to do this, but either way it might require some more work. The main limitation is that they limit the size and API set of apps made using a free plan; more app means more money. If we do want to investigate this further, we should talk to the MS people (what are their names again?) and see if we can get some sort of a budget (:money_with_wings:).

### Post-footnote afterthought comments
We should make sure that "The MS guys" are on this repo too so that they can see what's going on if they want to.

### Post-footnote afterthought comment addition
I _really_ need to remember their names.

### Post-footnote afterthought comment addition extension
I think this is the longest GitHub post I have ever written. Glad I didn't attempt it on my phone.

**Comment by WasabiFan** [comment]
@kyranstar What version of MonoGame do we want to use? The latest stable is `v3.2`, which didn't include the Content Pipeline. This lets us create assets without the need for old XNA tools, so it would be best in that respect if we used a newer alpha release. But that presents the issue of stability... so what do you think we should do?

**Comment by kyranstar** [comment]
I've personally never had any issues with stability so I wouldn't be the person to ask. In my opinion, I would pick the newer version if the content pipeline is a lot better.

**Comment by WasabiFan** [comment]
If we want to go with unstable releases, we'll have to chose a version to use universally to make sure that the versions align so that we don't hit any compatibility issues. I think I'll just chose today's nightly and we can all use that, at least for a while. We should be able to move to a stable 3.3 release when they get there.

In case you want to look through it, the nightly  build listing is [here](http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/).

**Comment by WasabiFan** [comment]
I have added a new solution and MonoGame project (in 2a38449cf55cdc36894d1b4fd77562cb139a1600). It contains no custom modifications, so it's just the default code right now. I will be setting up a common library and adding some other infrastructure code soon so that people can look through their parts if they want.

I added a wiki page [here](https://github.com/kyranstar/Hunt-The-Wumpus/wiki/Setting-up-your-local-environment----Installing-MonoGame) that explains how to install the dependencies. The easiest way to get Visual Studio is through [DreamSpark](https://www.dreamspark.com/Student/Default.aspx).

Anyway, I invite all of you to check it out!

**Comment by kyranstar** [comment]
How did you sign up as a student for DreamSpark? It says that LWSD is not registered with them when I tried to sign up with my email.

**Comment by WasabiFan** [comment]
I took a picture of my Student ID and attached it (I think it's one of the last options). You get access to the software automatically as soon as you submit it, so there's no waiting.

**Comment by WasabiFan** [comment]
I *think* I have added all the required files and docs so that you can run the basic sample that I have created. My goal with this is to get the final infrastructure set up and in place so that when we are ready to get started we can start writing code immediately.

If you get a chance, I'd like some of you to try following my instructions and make sure that everything works. Particularly, it would be great if someone can attempt to follow these instructions on their Windows 7 school laptops (but Windows 8 is helpful as well). I don't have enough time to explain how to use Git right now, so if you don't currently know how to clone our repo you won't be able to follow these instructions yet (sorry!).

The initial set-up instructions are [here](https://github.com/kyranstar/Hunt-The-Wumpus/wiki/Setting-up-your-local-environment-(Installing-MonoGame)). After following those, continue to the following steps to open and run the game:

1. Clone the repo. You can do this with Visual Studio or with the CLI.
2. Open Windows Explorer and browse to the cloned copy of our source code.
3. From there, browse to the `Final Game` folder and double-click `HuntTheWumpus.sln`. This should open Visual Studio.
4. Click the "Start" button (green arrow)
5. Stare in wonder (optional)

Hopefully, this will leave you with an image of a spinning cube overlaid on a field of [goldenrod](http://en.wikipedia.org/wiki/Goldenrod_(color)). If you encounter errors or something else doesn't work correctly, please tell me; that probably means I did something wrong.

**Comment by kyranstar** [comment]
![](http://i.imgur.com/luq9NK6.png) Windows 8 home computer

**Comment by WasabiFan** [comment]
Perfect! That means that the project setup *should* be completely ready. Whenever we decide to start development, my graphics stuff will be ready and not in our way.
