### ISSUE TITLE
Name and catchphrase for our game?

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#21]
I think we need a title and catchphrase for our game.

The title could be some play on words like "Pac-Man", "Ghost" and "Wumpus" ("Pac-Wumpus", anyone?). A catchphrase could be as simple as "Like Pac-Man, but different".

Any thoughts/suggestions? Putting something like this on our main menu along with a themed background would be pretty cool.

**Comment by nikbyk** [comment]
Hunt the Pac Man?


Sent by Outlook for Android





On Sun, May 17, 2015 at 10:38 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
I think we need a title and catchphrase for our game.

The title could be some play on words like "Pac-Man", "Ghost" and "Wumpus" ("Pac-Wumpus", anyone?). A catchphrase could be as simple as "Like Pac-Man, but different".

Any thoughts/suggestions? Putting something like this on our main menu along with a themed background would be pretty cool.

---
Reply to this email directly or view it on GitHub:
https://github.com/kyranstar/Hunt-The-Wumpus/issues/21

**Comment by WasabiFan** [comment]
I like that! It gives a definite nod to the original competition name.

**Comment by WasabiFan** [comment]
@kyranstar Why're we closing this?

**Comment by kyranstar** [comment]
It seemed like we had decided on a name. You can reopen if we want, but I doubt any more of our team will have very much input.
