### ISSUE TITLE
Theme changer for game?

### ISSUE THREAD

**Issue by nikbyk** [kyranstar/Hunt-The-Wumpus#22]
We should make a theme changer, I'll make assets. Get to work, slaves.

**Comment by kyranstar** [comment]
Sounds like this isn't happening.

**Comment by WasabiFan** [comment]
I think I could probably make it work, but there won't be any great "UI switch" -- it would have to be in the debug console. I might attempt it if I finish all this other stuff, but I'm probably being overly optimistic.
