### ISSUE TITLE
Game over scene

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#23]
We still need a game over scene for the game.

**Comment by WasabiFan** [comment]
It's already in there

**Comment by WasabiFan** [comment]
The game over scene appears when you finish fighting the Wumpus after a collision (whether you win or lost) and after you fail the questions after hitting a pit. We don't currently have any logic to handle shooting the Wumpus, nor does the game over scene tell you whether you won or lost (or what your score was).
