### ISSUE TITLE
Starting a new game doesn't reset the state

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#24]
If you finish a game and then start a new one, you are put in the state that you ended with previously.

**Comment by kyranstar** [comment]
e00c8a5 I sorta fixed this. It generates a new map, but it still shows the game over screen when you start the game. I'm not really sure how to fix this, so I'm going to leave it to you.

**Comment by WasabiFan** [comment]
Seems to be fixed with 0493f00025ab2bfa7fac560af1479dcb200747e4
