### ISSUE TITLE
Make the random algorithm make a rectangular grid (if that is really what we want)

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#26]
The spec says that the cave is supposed to be something like a 5x6 grid. Personally, I think the current haphazard caves that we have are pretty cool, but if we want the rectangular cave we should add those constraints sooner rather than later.

**Comment by kyranstar** [comment]
I don't think it actually says it has to be a grid. It just uses that for an example, so I vote that we shouldn't do this.

**Comment by kyranstar** [comment]
We decided not to in class
