### ISSUE TITLE
More GUI functionality

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#29]
From spec:

- [x] Display on the game screen a representation of the room, including the hexagonal form of the room, with each edge illustrated as either a tunnel to an adjacent room or a wall blocking access to an adjacent room.  Include an illustration of the player, any present hazards, the wumpus if present, and any additional graphics that add to the realism of the cave.
- [ ] Display on the game screen the player’s score.
- [x] Display on the game screen the player’s inventory.
- [ ] Display on the game screen any hints based on the player’s room. (For example: I smell a wumpus).
- [ ] Display on the game screen all actions the player can take on the current turn.
  - Move
  - Shoot an arrow
  - Purchase arrows
  - Purchase a secret

**Comment by WasabiFan** [comment]
I think the inventory is mostly there already, right? The arrows and gold?

On the score, I'm not quite sure if we want to include it. The score is calculated assuming the player killed the Wumpus (100 points - other stuff). Showing the score and then not saving it because they lost seems like a confusing experience. But, it should be very easy to implement, so I can try it out.

**Comment by WasabiFan** [comment]
I think we also need to decide how we want the GUI to look. I think it would be cool to make it look like an old-style arcade machine dashboard, but I don't know how that might work.

**Comment by kyranstar** [comment]
We could overlay an image like this

![](http://www.libertygames.co.uk/images/gallery/1141/1395-cosmic-four.jpg)

And just draw the game in the screen?

**Comment by kyranstar** [comment]
We could just draw the stats up top like in the original game.

**Comment by WasabiFan** [comment]
If we do this, we'll need:
- A shell image (like the one that you showed, but preferably more zoomed-in)
- Preferably some images of one of those arcade buttons in different states (at rest, pressed down) for buttons
- A font for the arcade-like screen. I'm not sure how to do this technically yet.

It would be extra cool if we got an old-looking monitor effect, like [this Linux program](https://github.com/Swordfish90/cool-retro-term).
