### ISSUE TITLE
Add warnings for wumpus/cave/bats

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#36]

**Comment by WasabiFan** [comment]
How do we want to do this graphically? The ideas that I have are:
- A "toast notification" style popup in the corner of the game
- A dedicated area in the UI for showing things like this that doesn't disappear
- A "speech bubble" type image that appears by the character
- An icon that appears over top of the grayed-out room (maybe with some flashing) -- this wouldn't have text

What do you guys think about this?

**Comment by kyranstar** [comment]
I think you're not supposed to know exactly which room contains the hazard,
so you can't do that last one. I think the speech bubble would look kinda
dumb too? We do have a lot of available UI space, so we could do the
dedicated space thing, or have it extend when warnings are in place.

**Comment by WasabiFan** [comment]
I have added these warnings to the GUI tray. It only shows one ATM, but I hope to show all of them in the future.
