### ISSUE TITLE
Updated to-do list:

### ISSUE THREAD

**Issue by anak4569** [kyranstar/Hunt-The-Wumpus#37]
Necessary:
-Render bats
-Render gold piles
-Render arrows
-Put a message for hazards 
-Load trivia questions
-5 hard coded maps/randomly generated maps
-Buy arrows and hints with trivia
-Add the hint system

Optional:
-Animations (Hazards, moving, shooting)
-Additional looping from side to side
-Updated main menu graphics
-Render gold and score for the user to see

-restarting the game

**Comment by WasabiFan** [comment]
When you get a chance, please open issues for items that don't already have issues open.

**Comment by kyranstar** [comment]
What does "render arrows" mean? Shooting animations?
