### ISSUE TITLE
Art needed

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#41]
Here's a list of "art" tasks that I think should be done:
- [ ] Crop the background image so that it can be repeated as a texture. This could be cropped so it's just one hexagonal cell.
- [x] Create a background for the menu screens. I think it would be nice to have some sort of art here.
- [x] A picture of the frame around an arcade machine display that we could overlay over the game.
- [x] Along with the point above, images of "arcade buttons" -- the big round ones -- in different states (pressed, unpressed, hovered) would be cool.
- [x] Dots for main menu animation
- [x] "Alert" icon (some shape with an exclamation point in it?) for displaying next to the warnings
- [x] "Turns" icon to put next to the move count (something like a circular arrow)
- [x] An icon to signify buying stuff (a plus and a dollar sign?) to put in the "purchase <stuff>" buttons

**Comment by kyranstar** [comment]
You mean like these?

![](https://d3fvptmknnj7i1.cloudfront.net/inline/pianocade-retro-synthesizer-2.jpg) I can do that.

**Comment by WasabiFan** [comment]
Those buttons look pretty close, although we'd need to try to depress them in Photoshop. I'll try it out and see it I can make it work.

**Comment by WasabiFan** [comment]
Of course, if you _can_ just make them in photoshop from the start that would be best.

**Comment by kyranstar** [comment]
Wait... I forgot that I'm totally awful at digital art

**Comment by WasabiFan** [comment]
@nikbyk ? ;)

**Comment by nikbyk** [comment]
Will do. Probly by tomorrow


Sent by Outlook for Android





On Sat, May 23, 2015 at 2:04 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk ? ;)

---

**Comment by nikbyk** [comment]
Right after I pulled I received my favorite texture importer error and can't run it anymore. @WasabiFan

**Comment by WasabiFan** [comment]
What build are you on? Have you installed _all_ Windows Updates?

**Comment by nikbyk** [comment]
10122, lemme check on updates


Sent by Outlook for Android





On Sat, May 23, 2015 at 3:36 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
What build are you on? Have you installed _all_ Windows Updates?

---

**Comment by nikbyk** [comment]
Installing all updates

**Comment by WasabiFan** [comment]
Can you record a list of all the uodates that it installs?

**Comment by nikbyk** [comment]
Still get the error. Not 30 tho. For the RoomGoldOverlay file

**Comment by nikbyk** [comment]
There was a firmware and windows defender update

**Comment by WasabiFan** [comment]
Restart the PC, start VS, do a clean, then a build, and tell me what happens

**Comment by nikbyk** [comment]
Still get the errors

**Comment by WasabiFan** [comment]
How many? And are they the texture ones?

**Comment by nikbyk** [comment]
2 just gold texture and some command exited with value of 1. Also, I accidentally pushed a revert to 8ce887a4

**Comment by nikbyk** [comment]
Reckoned and am now sitting with 31 errors

**Comment by nikbyk** [comment]
Recloned*

**Comment by nikbyk** [comment]
@kyranstar nice job :)

**Comment by WasabiFan** [comment]
> Also, I accidentally pushed a revert to  8ce887a 

Just revert the revert ;)

As for the errors, I'm really not sure... Can you run Windows 8 in a VM? I haven't gotten any useful replies...

**Comment by nikbyk** [comment]
Do you get the errors?

**Comment by nikbyk** [comment]
Theres this too
 Error	39	The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\Nikolay\Source\Repos\Hunt-The-Wumpus\Final Game\Content\Content.mgcb" /platform:Windows /outputDir:"C:\Users\Nikolay\Source\Repos\Hunt-The-Wumpus\Final Game\Platform\Desktop\Content\bin\Windows" /intermediateDir:"C:\Users\Nikolay\Source\Repos\Hunt-The-Wumpus\Final Game\Platform\Desktop\Content\obj\Windows" /quiet" exited with code 30.	Desktop

**Comment by WasabiFan** [comment]
That just means that there was an error with the texture generator, which you already know

**Comment by nikbyk** [comment]
wth is wrong tho. Shouldn't be 10122 then.

**Comment by WasabiFan** [comment]
> Do you get the errors?

Yes, I do. All we know at this point is that it is something that this build causes...

**Comment by nikbyk** [comment]
But it worked fine yesterday multiple times, so it's probably something we trigger

**Comment by WasabiFan** [comment]
When it worked, had you upgraded from a previous build or started from an empty drive? If you had previously built the project (while not on 10122) and then upgraded, the asset files would already be there when you ran a build, so it wouldn't try to generate them again. But I then added a file, so it didn't have an existing one and was forced to generate just that one -- that's why it was just one error. You then deleted and re-cloned, which deleted all the previously generated files, so you got all 30 or s  errors.

**Comment by nikbyk** [comment]
That makes sense. So we should just downgrade to 10074 until after the contest?

**Comment by WasabiFan** [comment]
Or check in our generated asset files... but I don't like that possibility. Have you tried running a VM of 8?

**Comment by nikbyk** [comment]
No, not yet, I don't have time to install 8 on a VM right now. Maybe you could try?

**Comment by WasabiFan** [comment]
OK; I'll try and see how it runs on the Surface ;)

**Comment by nikbyk** [comment]
Cool

**Comment by kyranstar** [comment]
You guys know we have a chat thing for a reason, right? Haha

**Comment by WasabiFan** [comment]
Yeah but we aren't very good at using tools in the way that they are intended :wink:

**Comment by WasabiFan** [comment]
We should track our source code in chat and communicate in a `txt` file in our repo

**Comment by WasabiFan** [comment]
@nikbyk I'm going to delete our conversation in this issue so that we can use it to track real stuff.

**Comment by nikbyk** [comment]
Ok


Sent by Outlook for Android





On Sat, May 23, 2015 at 10:27 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk I'm going to delete our conversation in this issue so that we can use it to track real stuff.

---

**Comment by WasabiFan** [comment]
I just added a little "Wumpus chase scene" to the main menu. It's still rough, but this creates a new required art piece: a dot. Just a single dot like the arrow image to trace the path as they move around the menu. Like the Pac-Man dots.

**Comment by WasabiFan** [comment]
@nikbyk I just added a few more things to this list ;)

**Comment by nikbyk** [comment]
Okay. Will get to them tonight. Regarding the errors, should I roll back to 10074?


Sent by Outlook for Android





On Sun, May 24, 2015 at 3:05 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk I just added a few more things to this list ;)

---

**Comment by nikbyk** [comment]
I'll make these probably by tonight, sorry for the delay. I am reinstalling 10074 first, though

**Comment by WasabiFan** [comment]
> I'll make these probably by tonight, sorry for the delay

It's fine ;) These images aren't really time-sensitive... any time before Thursday should work. They're pretty much just drop-in replacements.

I think the highest priority is the arcade theme -- so buttons and a frame. Then the last three icons on the list are second pri. The rest is mostly just polishing the shiny stuff.

**Comment by nikbyk** [comment]
added most of the pictures. Will finish the rest over the next day or so

**Comment by kyranstar** [comment]
Uhh... Why is everything yellow in the title screen? 
![image](https://cloud.githubusercontent.com/assets/5855296/7802614/662a51d2-02ee-11e5-9fe9-8eccab29a878.png)

**Comment by WasabiFan** [comment]
They look good!

On the hex background image, it doesn't look like it is tile-able (there's margin around it and some of the outline is cut off). In the end, this image will be tiled as a rectangular image, so it should probably be the edges of four or so cells -- I'd recommend that you make a pattern of four hexagons, and then crop it to the center points on each side. Something like this (crop line in yellow):

![foo](https://cloud.githubusercontent.com/assets/3310349/7802616/6b1c5898-02ee-11e5-8b5e-4f1829cdf9b1.PNG)

> Uhh... Why is everything yellow in the title screen? 

Because the dots that I used before were 1x1 px... these are much bigger.

**Comment by WasabiFan** [comment]
@kyranstar Try now... I changed the scale from 15x to 0.03x

**Comment by kyranstar** [comment]
@WasabiFan Yup, it works. Cool.

**Comment by nikbyk** [comment]
Will do


Sent by Outlook for Android





On Mon, May 25, 2015 at 2:59 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
They look good!

On the hex background image, it doesn't look like it is tile-able (there's margin around it and some of the outline is cut off). In the end, this image will be tiled as a rectangular image, so it should probably be the edges of four or so cells -- I'd recommend that you make a pattern of four hexagons, and then crop it to the center points on each side. Something like this (crop line in yellow):

![foo](https://cloud.githubusercontent.com/assets/3310349/7802616/6b1c5898-02ee-11e5-8b5e-4f1829cdf9b1.PNG)

> Uhh... Why is everything yellow in the title screen?

Because the dots that I used before were 1x1 px... these are much bigger.


---

**Comment by WasabiFan** [comment]
@nikbyk Can you remove the margin on the "turns" image? It's pretty small ATM.

For the "purchase" button, can you either:
- Make a duplicate that says "secret" instead of "arrow"
- Remove the text and make it just a single dollar (maybe with a + sign) so that it can be used in both instances

I just added the warning and turns icons to the GUI, and it looks pretty good. I recommend that you guys pull and check it out!

P.S. I moved some of the icons into the `Shared Code\GUI\Generated GUI\XAML Assets` folder -- don't update the one in `Content` or else it will be overwritten on build.

**Comment by WasabiFan** [comment]
@nikbyk Sorry for giving you all these little tasks!

**Comment by nikbyk** [comment]
Its okay


Sent by Outlook for Android





On Mon, May 25, 2015 at 4:10 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk Sorry for giving you all these little tasks!

---

**Comment by nikbyk** [comment]
Arcade images in

**Comment by WasabiFan** [comment]
Looks good. I'll add the render code and we can see how it looks.

**Comment by nikbyk** [comment]
alright

**Comment by nikbyk** [comment]
@WasabiFan How long do you think on the render code?

**Comment by WasabiFan** [comment]
Hhhhhh... I don't know, sadly. I think I am close to understanding the correct way to do it...? So... I'd say maximum an hour, hopefully less.

**Comment by WasabiFan** [comment]
I hope the confusion doesn't come through in my messages.

**Comment by nikbyk** [comment]
Okay, sounds good. I'm making buttons right now

**Comment by WasabiFan** [comment]
Great! If the game doesn't function, at least it will look pretty.

**Comment by WasabiFan** [comment]
Honestly, that's probably going to get us more points with the judges than adding actual hints :wink:

**Comment by nikbyk** [comment]
lol, true

**Comment by WasabiFan** [comment]
@nikbyk I just added the initial version of the frame renderer. The two sides are wider than half the viewport, so they overlap (without using the middle image yet). Can you make them thinner, and maybe remove one of the titles on the top? I think if we trim back the space that it takes up it will look pretty cool.

It also looks like they don't line up perfectly... they're off by a few pixels vertically.

**Comment by nikbyk** [comment]
rly? thats weird. I'll slim down the sides

**Comment by nikbyk** [comment]
done

**Comment by WasabiFan** [comment]
Here's what it looks like:
![capture](https://cloud.githubusercontent.com/assets/3310349/7829143/add9a514-03f2-11e5-8633-6a0912b8de3f.PNG)

I think that we should:
- Fix that cut-off part on the top (cut off the arm on the right side)
- Remove the dots on the bottom (so that we can put the UI counters there)
- Slim the side bars down some more, maybe to about 50%-60% of what it is now.

Overall it looks good, but I think we need to clear up some space so that it doesn't take up as much space. But overall, pretty good.

**Comment by nikbyk** [comment]
will do

**Comment by WasabiFan** [comment]
Can you actually cut out the part of the bottom bar (make it transparent) between the besels? I'd like to be able to render the GUI under it.

**Comment by nikbyk** [comment]
sure

**Comment by nikbyk** [comment]
done, can you make your gray bottom bar taller, to match the arcade frame?

**Comment by WasabiFan** [comment]
Yup; I'll take a look and start adjusting today and tomorrow.

**Comment by nikbyk** [comment]
also, hints and shit turn out to be behind the frame, too

**Comment by WasabiFan** [comment]
I know... I'll have to figure it out.

**Comment by nikbyk** [comment]
okay, is that all i need to do for today? I can finish the main menu image tomorrow

**Comment by WasabiFan** [comment]
Yup; sorry for all this! I'll work on adapting the UI.

**Comment by nikbyk** [comment]
it's alright

**Comment by WasabiFan** [comment]
@nikbyk I just pushed the majority of the updates that we'll need for the arcade frame (although some stuff still looks funky, and other parts just aren't adapted correctly). I think we can make the whole thing look cohesive if we continue the frame along the bottom and either:

- Cut a transparent hole between the bezels in the image and render the HUD under it
- Move the order so that it renders the HUD on top of the frame

The former is the easiest option (the other would require some code restructuring, which I'm not fully prepared to do). Can you try that out and see how it looks?

**Comment by nikbyk** [comment]
Didn't I already do that?


Sent by Outlook for Android





On Wed, May 27, 2015 at 2:34 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk I just pushed the majority of the updates that we'll need for the arcade frame (although some stuff still looks funky, and other parts just aren't adapted correctly). I think we can make the whole thing look cohesive if we continue the frame along the bottom and either:

- Cut a transparent hole between the bezels in the image and render the HUD under it
- Move the order so that it renders the HUD on top of the frame

The former is the easiest option (the other would require some code restructuring, which I'm not fully prepared to do). Can you try that out and see how it looks?

---

**Comment by WasabiFan** [comment]
I think I'm not being very descriptive with my wording ;) Currently, we have it so that the trapezoidal edges show up on the inside of the bottom frame (there is _no_ frame image in the bottom-center). I'm looking to remove the inner edges (the vertical bezel on the bottom) and make it a continuous bar like before but with the center cut out. Like this (rough cut):
![capture](https://cloud.githubusercontent.com/assets/3310349/7848299/639b2f8a-047f-11e5-83aa-282510c67c34.PNG)
Then we'd render the GUI with the same background color as on the rest of the frame so that you can't tell that there is a hole there.

**Comment by nikbyk** [comment]
Oh, I see. Okay. I'll get to that when I get home


Sent by Outlook for Android





On Wed, May 27, 2015 at 2:55 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
I think I'm not being very descriptive with my wording ;) Currently, we have it so that the trapezoidal edges show up on the inside of the bottom frame (there is _no_ frame image in the bottom-center). I'm looking to remove the inner edges (the vertical bezel on the bottom) and make it a continuous bar like before but with the center cut out. Like this (rough cut):
![capture](https://cloud.githubusercontent.com/assets/3310349/7848299/639b2f8a-047f-11e5-83aa-282510c67c34.PNG)
Then we'd render the GUI with the same background color as on the rest of the frame so that you can't tell that there is a hole there.

---

**Comment by nikbyk** [comment]
done

**Comment by WasabiFan** [comment]
@nikbyk Can you make the arrow picture in `Final Game/Shared Code/GUI/Generated GUI/XAML Assets` fewer dots? Maybe half or 1/3 as many? They don't show up well when I render it in the tray.
