### ISSUE TITLE
Discussing stuff

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#43]
@nikbyk 
> Okay. Will get to them tonight. Regarding the errors, should I roll back to 10074?

It's your choice. If you don't have an issue with not having the latest build and are O.K. with taking the risks of rolling back, go for it -- it'll make your life a lot easier if you don't have to get around these errors. Otherwise, I really don't know what we can do about it other than use a different machine...

I haven't gotten a chance to try out that VM, though.

**Comment by kyranstar** [comment]
Does anybody know whether we're supposed to bring lunch to the competition?

**Comment by WasabiFan** [comment]
The schedule that we were given doesn't specify...

**Comment by nikbyk** [comment]
No, we don't. MSFT will feed us, along with free money for company store.

**Comment by nikbyk** [comment]
If anyone wants to join me, I'll be there around 9:25, maybe we can do some finishing touches

**Comment by WasabiFan** [comment]
I'll probably be there by then too; I guess I'll come by the competition area early (around then) and we can get set up and apply finishing touches.

@NickSiBo Don't break or forget your laptop -- it _is_ our fate.

**Comment by nikbyk** [comment]
@WasabiFan great
