### ISSUE TITLE
How do we want to handle arrow purchase?

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#44]
In the spec, it says:
> You can purchase 2 more arrows by getting at least 2 out of three trivia questions right.

There are two interpretations that I can take away from reading that:
- Asking to purchase arrows and then correctly answering 2/3 questions gives you two arrows, and you can do this as many times as you want
- Asking to purchase arrows and then correctly answering 2/3 questions gives you one arrow, and you are only permitted to do this twice

Which one do we like best?

**Comment by kyranstar** [comment]
I like the second one. It makes the game actually somewhat hard.

**Comment by WasabiFan** [comment]
You can now purchase arrows, although it doesn't limit the number of arrows yet.
