### ISSUE TITLE
Label turn number

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#46]
I think the turn number in the corner of the GUI is a bit confusing. At first, since it was next to hints, I thought i meant I had 85 hints ready.

I think we label it: `Turns: 85`

**Comment by WasabiFan** [comment]
My plan is to add an icon to disambiguate it. It looks like @nikbyk just checked the box in the "art" issue and made a commit, so my guess is that it's done -- I'll add this icon in the UI shortly.

**Comment by WasabiFan** [comment]
I think we can call this done -- as soon as @nikbyk gets a chance to resize the image, it should look good too.
