### ISSUE TITLE
Making trivia answers less obvious

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#49]
Currently, the first answer is always the correct one. Can we fix this? The two places that I think this would be easiest are on load, when it takes the questions from the file, and at render time (when it gives the set of answers from the context).

Anyone willing to give this a shot?

**Comment by anak4569** [comment]
Sure, I can do this. I was just wondering, where should I put the hints? In the secret manager?

**Comment by WasabiFan** [comment]
> Sure, I can do this

You'll probably want to try randomizing the `AnswerChoices` in each question around [here](https://github.com/kyranstar/Hunt-The-Wumpus/blob/master/Final%20Game/Shared%20Code/Trivia/Trivia.cs#L41).

> I was just wondering, where should I put the hints? In the secret manager or the trivia file?

It's those lines that add to the `LockedHints` [here](https://github.com/kyranstar/Hunt-The-Wumpus/blob/master/Final%20Game/Shared%20Code/Trivia/Trivia.cs#L33). I recommend that you read through our list of trivia questions, pick some, and add hints that supply background or narrow down the answers.
