### ISSUE TITLE
Flow chart?

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#5]
I am looking at this tool that we found and it really isn't working. It's glitchy and not easy to use, and you can't export without paying. Does anyone have any other ideas for tools to use?

**Comment by kyranstar** [comment]
[This is the tool I used before](https://conceptboard.com/board/rxm5-r19t-adr7-npq4-ut2m), which worked pretty well.

**Comment by WasabiFan** [comment]
It works well! I just took a few minutes to start on a draft chart and like the tool. @kyranstar Can you take a look at it and tell me what you think?

P.S. I don't want to do all the work myself, nor do I want for any of you to not be able to work because I am doing all of it. But we need to start getting stuff done (start discussing things, start collaborating on a game architecture, etc.), so I am trying to spend some of my extra time working on this.

**Comment by BlueRosesSonyPony** [comment]
Can you send me the flowchart? Thanks.

**Comment by WasabiFan** [comment]
Here it is: https://conceptboard.com/board/rxm5-r19t-adr7-npq4-ut2m

**Comment by BlueRosesSonyPony** [comment]
Thanks!
