### ISSUE TITLE
GUI doesn't fit to screen

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#51]
This happens on my computer. I'm not sure why, I just hope it doesn't happen on the demo computer.

![image](https://cloud.githubusercontent.com/assets/5855296/7850545/7e21024e-0498-11e5-96a4-032d31c153e0.png)

**Comment by WasabiFan** [comment]
That is expected ATM; I have committed some fixes locally, but don't want to push them because they break some other functionality. I should have it ready to push in ~10 mins.

**Comment by WasabiFan** [comment]
I just pushed the fixed GUI. Can you take a look when you have some time and make sure that it looks right on your display?

**Comment by kyranstar** [comment]
It looks good, but the hints don't scroll horizontally. Is there any way you could do that, or at least reduce the font size?

![image](https://cloud.githubusercontent.com/assets/5855296/7850882/94c44638-049c-11e5-9886-778106d7023b.png)

**Comment by WasabiFan** [comment]
I just pushed a fix for this. I think I also want to make this flyout render wider and above the trivia screen when trivia is open, so that you can reference it as you answer questions.

**Comment by nikbyk** [comment]
Also, shouldn't there be a screen that pops up if you miss the Wumpus? If you dont look at the log, you don't know that you haven't hit it.

**Comment by WasabiFan** [comment]
If you don't hit it, the game won't end... it definitely isn't optimal, but I don't have enough time to set up a notification stream.

**Comment by nikbyk** [comment]
ok, I fixed the red color if you miss, so at least we have that

**Comment by WasabiFan** [comment]
Can we close this?
