### ISSUE TITLE
OrderBy appears to get stuck in a loop

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#53]
@kyranstar When I run the game, it keeps freezing in an infinite loop in `SetInitialPosition` -- the `OrderBy` call just infinitely evaluates the sort order. Are you sure that that algorithm won't get stuck if the pathfinding doesn't return the same result for backwards paths? My guess is that it's something like that.

**Comment by WasabiFan** [comment]
I should mention that it is only ~20% of the time -- probably based on the map that was generated.

**Comment by kyranstar** [comment]
Strange... I'll see.

**Comment by kyranstar** [comment]
Apparently the FindPath method is what is freezing up... Weird.

**Comment by WasabiFan** [comment]
@kyranstar Any progress on this? This is pretty important to fix before tomorrow... if we can't fix it, we need to bypass it.

**Comment by kyranstar** [comment]
I don't know.. Probably pybass it unless you want to take a look at it?

**Comment by WasabiFan** [comment]
I vote that we remove the `OrderBy` call and instead put it in a dictionary and find the highest value that way... if it's really this funky, we can just write that small section ourselves.

**Comment by kyranstar** [comment]
I don't really think that'll work because it's the pathfinding code that has the issue?

**Comment by WasabiFan** [comment]
Oh... What's the issue with the pathfinding? Is it the one that is freezing?

**Comment by kyranstar** [comment]
Yeah, It's somewhere in the method.

**Comment by WasabiFan** [comment]
Crap... I'm not familiar enough with how that pathfinding works to offer much that's useful. If you can't figure it out, bypass it however you can and we'll just have to hope for the best. Why doesn't this happen during the game? Why is it just when it's finding an initial position?
