### ISSUE TITLE
Hunt the Wumpus Time and Location:

### ISSUE THREAD

**Issue by anak4569** [kyranstar/Hunt-The-Wumpus#54]
What time specifically and what building specifically should I be at tomorrow? I know it's gonna start around 9:30, but I have no idea which building it is.

**Comment by WasabiFan** [comment]
The schedule was in the packet with the other forms that we got a few weeks ago:
Arrival is 9:45-10:00, and departure is 5:00. It's in Microsoft building 92.

**Comment by anak4569** [comment]
Has anyone else already arrived
