### ISSUE TITLE
Does the map need to change while the game is running?

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#6]
I am currently writing the code to render a basic map. Can I assume that no rooms' connections are changed while the user is in a game?

**Comment by kyranstar** [comment]
Probably. I mean, unless we really wanted to confuse the user.

**Comment by WasabiFan** [comment]
OK :wink: I'll write it to only lay out the map once for each game. If we decide to add a "ludicrous difficulty" mode, we may need to revisit this decision.
