### ISSUE TITLE
Dealing with infinite room loop?

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#9]
How do we want to handle the fact that the map wraps from one edge to the other? I was thinking we could render the rooms adjacent to the edges and move the player to the other side of the map when they try to cross. In that case, we would have to manually store the information on which connection is supposed to wrap to make sure that the layout algorithm doesn't hit an infinite loop.

Any other ideas?

And while we are on the subject, how do we want to obscure adjacent rooms from the user? Fog?

**Comment by kyranstar** [comment]
For each render, we could also store whether the render pass has already shown that room as well in order to not loop infinitely. 

Also, fog is cool. Civilization V? ![](http://i590.photobucket.com/albums/ss344/PoweredBySoy/Games/FirstBerlin.jpg)

**Comment by WasabiFan** [comment]
> For each render, we could also store whether the render pass has already shown that room as well in order to not loop infinitely.

That sounds like it should work, although I'll need to implement it before I find any unexpected issues.

**Comment by nikbyk** [comment]
I had that figured out. I'll draw up a picture later, but all we need is the room connections list. Like say room 1 connects to 2,3,29. If you go off the end from room 1, the door would send you to 29. Idk if that makes sense. Ill draw up a diagram and email it later, which should make it clearer.





        Sent by Outlook for Android




On Mon, Apr 6, 2015 at 9:02 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
How do we want to handle the fact that the map wraps from one edge to the other? I was thinking we could render the rooms adjacent to the edges and move the player to the other side of the map when they try to cross. In that case, we would have to manually store the information on which connection is supposed to wrap to make sure that the layout algorithm doesn't hit an infinite loop.

Any other ideas?

And while we are on the subject, how do we want to obscure adjacent rooms from the user? Fog?

---
Reply to this email directly or view it on GitHub:
https://github.com/kyranstar/Hunt-The-Wumpus/issues/9

**Comment by WasabiFan** [comment]
> I had that figured out. I'll draw up a picture later, but all we need is the room connections list. Like say room 1 connects to 2,3,29. If you go off the end from room 1, the door would send you to 29. Idk if that makes sense. Ill draw up a diagram and email it later, which should make it clearer.

What we are discussing is how we want to render that effect, not the mechanic itself. As it currently stands, if we give one of those edge rooms a connection to the other side, it should work; but it will still look like you are hitting the edge of the map before wrapping. My question was just if we want to render the rooms to make it look like an infinite wrap or if we want to use some other sort of graphic (I think the decision was that we would render it as an infinite cave).

**Comment by nikbyk** [comment]
Oops, sorry misunderstood. I think we should render it so it looks like any other move to another room. Don't need to be special.





        Sent by Outlook for Android




On Tue, Apr 7, 2015 at 7:02 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
> I had that figured out. I'll draw up a picture later, but all we need is the room connections list. Like say room 1 connects to 2,3,29. If you go off the end from room 1, the door would send you to 29. Idk if that makes sense. Ill draw up a diagram and email it later, which should make it clearer.

What we are discussing is how we want to render that effect, not the mechanic itself. As it currently stands, if we give one of those edge rooms a connection to the other side, it should work; but it will still look like you are hitting the edge of the map before wrapping. My question was just if we want to render the rooms to make it look like an infinite wrap or if we want to use some other sort of graphic (I think the decision was that we would render it as an infinite cave).

---

**Comment by WasabiFan** [comment]
@nikbyk Would you like me to push the code that I [mentioned](https://github.com/kyranstar/Hunt-The-Wumpus/commit/4c31d5bfce59a9950c00172b83091f90d87889e6#commitcomment-10596474)? I recommend that you start thinking about at least that simple version of the generation algorithm now.

**Comment by nikbyk** [comment]
I know how to randomly generate caves, I just need to figure out a way to code it. I started, and will work more on that tomorrow.





        Sent by Outlook for Android




On Tue, Apr 7, 2015 at 7:44 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk Would you like me to push the code that I [mentioned](https://github.com/kyranstar/Hunt-The-Wumpus/commit/4c31d5bfce59a9950c00172b83091f90d87889e6#commitcomment-10596474)? I recommend that you start thinking about at least that simple version of the generation algorithm now.

---

**Comment by anak4569** [comment]
Who's currently working on graphics? I wanna start working on them, so I need to know what resolution, size, color scheme and theme we're going for.

**Comment by WasabiFan** [comment]
> Who's currently working on graphics? I wanna start working on them, so I need to know what resolution, size, color scheme and theme we're going for.

I'm the one working on graphics (rendering the scenes, loading the content). Are you saying that you want to start making assets (images, animations, audio, etc.)? If so, I'd recommend that you hold off on that until after we have our game mostly working.

Honestly, I won't know what our preferred format/size is until I have some time to do some research, and right now I'm focused on getting the framework written so that as you start having code ready it can be tested immediately. Past that, we haven't decided on the style of the graphics or the theme, which would make it very hard to start making images that fit that theme.

So, if you would like to work on temporary images to use for testing, go ahead -- we will need those. But if you are just looking for more things to work on, I'm sure I could write a more detailed to-do list so people always know what work they can take on when they want it.

**Comment by kyranstar** [comment]
I know that assets take a lot of time, so I think we should discuss our
theme and all of the those specifics when we get together next Friday, so
we don't end up with partially done assets in June.
